version: '3.8'

services:
  postgres:
    container_name: AdvertisementsDB
    image: postgres:14.0
    env_file: .env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=advertisements
    volumes:
      - ./.sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "exit 0"

  django:
    container_name: AdvertisementsAPP
    image: django:1.10-python3
    build: .
    env_file: .env
    ports:
      - ${DJANGO_EXTERNAL_PORT}:8001
    depends_on:
      postgres:
        condition: service_healthy
