version: '3.8'

services:
  postgres:
    container_name: AdvertisementsDB
    image: postgres:14.0
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "exit 0"

  django:
    container_name: AdvertisementsAPP
    build: .
    image: django_rest_framework
    ports:
      - ${DJANGO_EXTERNAL_PORT}:8001
    depends_on:
      postgres:
        condition: service_healthy

  angular:
    container_name: AdvertisementsAngular
    build: ./.angular/AdvertisementsAngular/
    image: angular
    ports:
      - ${ANGULAR_EXTERNAL_PORT}:4200
    depends_on:
      - postgres
      - django
