version: '3.8'

services:
  postgres:
    container_name: AdvertisementsDB
    image: postgres:14.0
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=advertisements
    volumes:
      - ./.sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "exit 0"

  django:
    container_name: AdvertisementsAPP
    build: .
    image: django_rest_framework
    env_file: .env
    ports:
      - ${DJANGO_EXTERNAL_PORT}:8001
    depends_on:
      postgres:
        condition: service_healthy

  angular:
    container_name: AdvertisementsAngular
    image: angular
    build: ./.angular/AdvertisementsAngular/
    env_file: .env
    ports:
      - ${ANGULAR_EXTERNAL_PORT}:4200
    depends_on:
      - postgres
      - django
