# Generated by Django 3.2.7 on 2021-10-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_rename_category_id_offer_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='offer',
            table='offer',
        ),
    ]
