# Generated by Django 3.2.7 on 2021-10-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20211003_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AlterField(
            model_name='offer',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='advertisements.category'),
        ),
    ]
